# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: es_copy 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "es_copy"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["John Jansen"]
  s.date = "2015-11-02"
  s.description = "Copy an Elasticsearch index ... Somewhere"
  s.email = "john.jansen@me.com"
  s.executables = ["es_copy"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".DS_Store",
    ".document",
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/es_copy",
    "es_copy.gemspec",
    "features/es_copy.feature",
    "features/step_definitions/es_copy_steps.rb",
    "features/support/env.rb",
    "fixtures/get_settings_expected.json",
    "fixtures/vcr_cassettes/create_index.yml",
    "fixtures/vcr_cassettes/get_settings.yml",
    "fixtures/vcr_cassettes/index_exists.yml",
    "fixtures/vcr_cassettes/index_missing.yml",
    "fixtures/vcr_cassettes/kitchen_sink.yml",
    "lib/es_copy.rb",
    "lib/es_copy/connection.rb",
    "lib/es_copy/engine.rb",
    "lib/es_copy/settings.rb",
    "spec/connection_spec.rb",
    "spec/engine_spec.rb",
    "spec/settings_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/johnjansen/es_copy"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Copy an Elasticsearch index ... Somewhere"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<elasticsearch>, ["~> 1.0.14"])
      s.add_runtime_dependency(%q<addressable>, ["~> 2.3.8"])
      s.add_development_dependency(%q<rspec>, ["~> 3.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<awesome_print>, ["~> 1.6.1"])
      s.add_development_dependency(%q<rubocop>, ["~> 0.34.2"])
      s.add_development_dependency(%q<webmock>, ["~> 1.22.2"])
      s.add_development_dependency(%q<vcr>, ["~> 2.9.3"])
    else
      s.add_dependency(%q<elasticsearch>, ["~> 1.0.14"])
      s.add_dependency(%q<addressable>, ["~> 2.3.8"])
      s.add_dependency(%q<rspec>, ["~> 3.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<awesome_print>, ["~> 1.6.1"])
      s.add_dependency(%q<rubocop>, ["~> 0.34.2"])
      s.add_dependency(%q<webmock>, ["~> 1.22.2"])
      s.add_dependency(%q<vcr>, ["~> 2.9.3"])
    end
  else
    s.add_dependency(%q<elasticsearch>, ["~> 1.0.14"])
    s.add_dependency(%q<addressable>, ["~> 2.3.8"])
    s.add_dependency(%q<rspec>, ["~> 3.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<awesome_print>, ["~> 1.6.1"])
    s.add_dependency(%q<rubocop>, ["~> 0.34.2"])
    s.add_dependency(%q<webmock>, ["~> 1.22.2"])
    s.add_dependency(%q<vcr>, ["~> 2.9.3"])
  end
end

